#!/reg/g/pcds/pkg_mgr/release/python/2.7.5/x86_64-rhel7-gcc48-opt/bin/python
#import argparse
import sys

#parser = argparse.ArgumentParser(description='Search directoryNotes.')
#parser.add_argument('integers', metavar='N', type=int, nargs='+',help='an integer for the accumulator')
#parser.add_argument('--sum', dest='accumulate', action='store_const',const=sum, default=max,help='sum the integers (default: find the max)')

#args = parser.parse_args()

f = open("/reg/neh/home5/sioan/Desktop/softXRayDataAndControls/directoryNotes.txt")

myString = sys.argv[1]

myLines = []
myBuffer = ["","","","","","","","",""]
alreadyPrintedLines = []

for i in f:
	try:
		myBuffer = myBuffer[1:]
		myBuffer.append(i)
	
		if myString in myBuffer[2]:

			for j in myBuffer:
				if j not in alreadyPrintedLines: 
					print j,
					alreadyPrintedLines.append(j)

	except:
		continue
