#!/bin/bash
source /reg/d/iocCommon/All/xpp_env.sh
#export PROCSERV="/reg/g/pcds/package/epics/3.14/extensions/R3.14.12/bin/$EPICS_HOST_ARCH/procServ --allow --ignore ^D^C --logstamp --noautorestart"
export TIME=`date +%s`
export NAME="monitor-cube.$HOSTNAME.$TIME"
export PATH=$PATH:/reg/g/xpp/scripts:/reg/neh/operator/xppopr/bin

CURREXP=`get_curr_exp`
cd /reg/d/psdm/xpp/$CURREXP/results/littleData/xppmodules/scripts
$PROCSERV --logfile /tmp/$NAME --name monitor-cube 40002 ./monitor-cube
